/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zrk_Main */

#ifndef _Included_com_zrk_Main
#define _Included_com_zrk_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zrk_Main
 * Method:    natvieMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zrk_Main_natvieMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
