/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_via_opencv_natives_OpencvManager */

#ifndef _Included_com_via_opencv_natives_OpencvManager
#define _Included_com_via_opencv_natives_OpencvManager
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_via_opencv_natives_OpencvManager
 * Method:    focusCheck
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_via_opencv_natives_OpencvManager_focusCheck
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
